# Generated by Django 4.2.1 on 2024-05-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
