# Generated by Django 4.2.1 on 2024-11-07 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_post_audio_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='audio_file',
        ),
    ]
