# Generated by Django 4.2.1 on 2024-05-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gay',
            field=models.BooleanField(default=True),
        ),
    ]
